from enum import StrEnum


class DriverStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    ASSIGNED = "ASSIGNED"
    OFF_DUTY = "OFF_DUTY"
    UNAVAILABLE = "UNAVAILABLE"


class ConstraintViolationCode(StrEnum):
    DRIVER_NOT_AVAILABLE = "DRIVER_NOT_AVAILABLE"
    EQUIPMENT_MISMATCH = "EQUIPMENT_MISMATCH"
    PICKUP_WINDOW_MISSED = "PICKUP_WINDOW_MISSED"
    DELIVERY_WINDOW_MISSED = "DELIVERY_WINDOW_MISSED"
    HOS_INSUFFICIENT = "HOS_INSUFFICIENT"
    HOME_TIME_VIOLATION = "HOME_TIME_VIOLATION"


class OperationalDisruptionType(StrEnum):
    DRIVER_DETENTION = "DRIVER_DETENTION"
    HOS_REDUCTION = "HOS_REDUCTION"
    HOME_DEADLINE_CHANGE = "HOME_DEADLINE_CHANGE"
    DRIVER_UNAVAILABLE = "DRIVER_UNAVAILABLE"


class AssignmentChangeType(StrEnum):
    PRESERVED = "PRESERVED"
    REMOVED = "REMOVED"
    ADDED = "ADDED"
