from datetime import datetime, timedelta, timezone

from app.domain.enums import DriverStatus, OperationalDisruptionType
from app.domain.models import Driver, Load, OperationalDisruption

ET = timezone(timedelta(hours=-4), name="EDT")


def _dt(day: int, hour: int, minute: int = 0) -> datetime:
    return datetime(2025, 3, day, hour, minute, tzinfo=ET)


DEMO_DRIVERS: tuple[Driver, ...] = (
    Driver(
        "DRV-001",
        "Maya Torres",
        "Atlanta",
        "GA",
        _dt(10, 7),
        660,
        "Atlanta",
        "GA",
        None,
        "DRY_VAN",
        DriverStatus.AVAILABLE,
    ),
    Driver(
        "DRV-002",
        "Eli Brooks",
        "Savannah",
        "GA",
        _dt(10, 7),
        480,
        "Charlotte",
        "NC",
        _dt(10, 18),
        "REEFER",
        DriverStatus.AVAILABLE,
    ),
    Driver(
        "DRV-003",
        "Nora Patel",
        "Charlotte",
        "NC",
        _dt(10, 6, 30),
        600,
        "Charlotte",
        "NC",
        None,
        "DRY_VAN",
        DriverStatus.AVAILABLE,
    ),
    Driver(
        "DRV-004",
        "Caleb Reed",
        "Jacksonville",
        "FL",
        _dt(10, 8),
        300,
        "Jacksonville",
        "FL",
        None,
        "FLATBED",
        DriverStatus.AVAILABLE,
    ),
    Driver(
        "DRV-005",
        "Imani Lewis",
        "Macon",
        "GA",
        _dt(10, 9),
        540,
        "Macon",
        "GA",
        None,
        "DRY_VAN",
        DriverStatus.AVAILABLE,
    ),
    Driver(
        "DRV-006",
        "Owen Price",
        "Columbia",
        "SC",
        _dt(10, 7),
        420,
        "Columbia",
        "SC",
        None,
        "REEFER",
        DriverStatus.ASSIGNED,
    ),
    Driver(
        "DRV-007",
        "Sofia Nguyen",
        "Orlando",
        "FL",
        _dt(10, 6),
        300,
        "Tampa",
        "FL",
        None,
        "DRY_VAN",
        DriverStatus.AVAILABLE,
    ),
    Driver(
        "DRV-008",
        "Marcus Hill",
        "Greenville",
        "SC",
        _dt(10, 10),
        180,
        "Greenville",
        "SC",
        None,
        "FLATBED",
        DriverStatus.OFF_DUTY,
    ),
)


DEMO_LOADS: tuple[Load, ...] = (
    Load(
        "LOAD-001",
        "Atlanta",
        "GA",
        "Charlotte",
        "NC",
        _dt(10, 8),
        _dt(10, 10),
        _dt(10, 12),
        _dt(10, 15),
        240,
        30,
        185000,
        "DRY_VAN",
        True,
    ),
    Load(
        "LOAD-002",
        "Savannah",
        "GA",
        "Orlando",
        "FL",
        _dt(10, 9),
        _dt(10, 11),
        _dt(10, 14),
        _dt(10, 18),
        270,
        45,
        220000,
        "REEFER",
        False,
    ),
    Load(
        "LOAD-003",
        "Charlotte",
        "NC",
        "Richmond",
        "VA",
        _dt(10, 10),
        _dt(10, 12),
        _dt(10, 14),
        _dt(10, 18),
        240,
        20,
        175000,
        "DRY_VAN",
        False,
    ),
    Load(
        "LOAD-004",
        "Jacksonville",
        "FL",
        "Atlanta",
        "GA",
        _dt(10, 11),
        _dt(10, 13),
        _dt(10, 15),
        _dt(10, 20),
        300,
        25,
        245000,
        "FLATBED",
        False,
    ),
    Load(
        "LOAD-005",
        "Macon",
        "GA",
        "Birmingham",
        "AL",
        _dt(10, 13),
        _dt(10, 15),
        _dt(10, 16),
        _dt(10, 20),
        180,
        35,
        145000,
        "DRY_VAN",
        False,
    ),
    Load(
        "LOAD-006",
        "Columbia",
        "SC",
        "Raleigh",
        "NC",
        _dt(10, 14),
        _dt(10, 16),
        _dt(10, 18),
        _dt(10, 21),
        210,
        40,
        165000,
        "REEFER",
        False,
    ),
    Load(
        "LOAD-007",
        "Orlando",
        "FL",
        "Miami",
        "FL",
        _dt(10, 15),
        _dt(10, 17),
        _dt(10, 19),
        _dt(10, 23),
        300,
        30,
        190000,
        "DRY_VAN",
        False,
    ),
    Load(
        "LOAD-008",
        "Greenville",
        "SC",
        "Knoxville",
        "TN",
        _dt(10, 16),
        _dt(10, 18),
        _dt(10, 20),
        _dt(10, 23),
        180,
        30,
        155000,
        "FLATBED",
        False,
    ),
    Load(
        "LOAD-009",
        "Atlanta",
        "GA",
        "Nashville",
        "TN",
        _dt(10, 18),
        _dt(10, 20),
        _dt(10, 22),
        _dt(11, 2),
        300,
        45,
        205000,
        "DRY_VAN",
        False,
    ),
    Load(
        "LOAD-010",
        "Charlotte",
        "NC",
        "Charleston",
        "SC",
        _dt(10, 19),
        _dt(10, 21),
        _dt(10, 23),
        _dt(11, 2),
        210,
        35,
        160000,
        "REEFER",
        False,
    ),
    Load(
        "LOAD-011",
        "Tampa",
        "FL",
        "Mobile",
        "AL",
        _dt(10, 20),
        _dt(10, 22),
        _dt(11, 2),
        _dt(11, 5),
        420,
        60,
        280000,
        "DRY_VAN",
        False,
    ),
    Load(
        "LOAD-012",
        "Raleigh",
        "NC",
        "Boston",
        "MA",
        _dt(10, 7),
        _dt(10, 7, 15),
        _dt(10, 18),
        _dt(10, 20),
        720,
        180,
        390000,
        "TANKER",
        False,
    ),
)


def get_demo_disruption() -> OperationalDisruption:
    return OperationalDisruption(
        id="DISR-001",
        type=OperationalDisruptionType.DRIVER_DETENTION,
        driver_id="DRV-001",
        occurred_at=_dt(10, 7),
        detention_minutes=180,
        hos_reduction_minutes=None,
        new_home_deadline=None,
        reason="Customer detention at previous stop",
    )
